version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: nuget
    directory: /tools/vl-map
    schedule:
      interval: weekly

  - package-ecosystem: nuget
    directory: /tools/vl-mcp
    schedule:
      interval: weekly

  - package-ecosystem: nuget
    directory: /tools/vl-probe
    schedule:
      interval: weekly
