version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: nuget
    directory: /src/VL.Agent
    schedule:
      interval: weekly

  - package-ecosystem: nuget
    directory: /src/VL.Agent.Map
    schedule:
      interval: weekly

  - package-ecosystem: nuget
    directory: /src/VL.Agent.Mcp
    schedule:
      interval: weekly

  - package-ecosystem: nuget
    directory: /src/VL.Agent.Probe
    schedule:
      interval: weekly
